---

#include_vars:
#  - vars-global.yml
vars:
  stack_name: test
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0

templates:
  - src: templates/docker-compose.yml.j2
    dest: stacks/{{ stack_name }}/docker-compose.yml
    vars:
      with_zookeeper: true
      ZOOKEEPER_NODES: 1
      CONFLUENT_PLATFORM_VERSION: 5.3.0

      with_kafka_broker: true
      volume_map_data: true
      KAFKA_BROKER_NODES: 3
      KAFKA_DELETE_TOPIC_ENABLE: false
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

      with_schema_registry: true
      with_kafka_connect: true
      KAFKA_CONNECT_NODES: 2
      with_ksqldb: false
      with_kafka_restproxy: false
      with_kafka_mqttproxy: false
      with_schema_registry_ui: false
      with_kafka_connect_ui: false
      with_kafka_manager: false
      with_kafkahq: false
      with_burrow: false
      
      with_hadoop: true
      HADOOP_DATANODES: 2

      with_spark: true
      SPARK_WORKERS: 2
      with_hive: true
      with_zeppelin: true
      with_jupyter: true


      # Visualization
      with_grafana: false
      with_kibana: false
      with_superset: false

      # NoSQL
      with_redis: false
      with_cassandra: false
      with_mongo: false
      with_neo4j: false
      with_elasticsearch: false
      with_tile38: false

      # RDBMS
      with_mysql: false
      with_sqlserver: true
      with_postgresql: false
      with_adminer: false

      # Event Store
      with_axon: false

      # MQTT
      with_mqtt: false
      use_mosquitto: false
      use_hivemq: false
      with_mqtt_ui: false

      with_minio: false
