---

#include_vars:
#  - vars-global.yml
vars:
  stack_name: test
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  confluent_platform_version: 5.3.0
  zoonavigator_version: 0.5.1
  ksql_db_version: 0.6.0
  schema_registry_ui_version: 0.9.5
  kafka_connect_ui_version: 0.9.7
  kafka_manager_version: LATEST
  kafka_kafdrop_version: LATEST
  kafka_kadmin_version: LATEST
  kafka_kafkahq_version: LATEST
  kafka_burrow_version: 1.2.0
  kafka_burrow_ui_version: 1.1.0
  kafka_burrow_dashboard_version: 1.0.4


templates:
  - src: templates/docker-compose.yml.j2
    dest: stacks/{{ stack_name }}/docker-compose.yml
    vars:
      #zookeeper
      ZOOKEEPER_enabled: true
      ZOOKEEPER_nodes: 1


      #kafka

      KAFKA_enabled: true
      KAFKA_volume_map_data: true
      KAFKA_broker_nodes: 3
      KAFKA_delete_topic_enable: false
      KAFKA_auto_create_topics_enable: true

      #kafka schema registry

      KAFKA_schema_registry_enabled: true

      #kafka connect

      KAFKA_connect_enabled: true
      KAFKA_connect.nodes: 2

      #misc kafka 'addons'

      KAFKA_ksqldb_enabled: true
      KAFKA_restproxy_enabled: true
      KAFKA_mqttproxy_enabled: true
      KAFKA_schema_registry_ui_enabled: true
      KAFKA_connect_ui_enabled: true
      KAFKA_manager_enabled: true
      KAFKA_kafdrop_enabled: true
      KAFKA_kadmin_enabled: true
      KAFKA_kafkahq_enabled: true
      KAFKA_burrow_enabled: true

      #hadoop
      with_hadoop: false
      HADOOP_DATANODES: 2

      with_spark: false
      SPARK_WORKERS: 2
      with_hive: false
      with_zeppelin: false
      with_jupyter: false


      # Visualization
      with_grafana: false
      with_kibana: false
      with_superset: false

      # NoSQL
      with_redis: false
      with_cassandra: false
      with_mongo: false
      with_neo4j: false
      with_elasticsearch: false
      with_tile38: false

      # RDBMS
      with_mysql: false
      with_sqlserver: true
      with_postgresql: false
      with_adminer: false

      # Event Store
      with_axon: false

      # MQTT
      with_mqtt: false
      use_mosquitto: false
      use_hivemq: false
      with_mqtt_ui: false

      with_minio: false
