---

#include_vars:
#  - vars-global.yml
vars:
  stack_name: tvd-generator
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  container_restart_policy: unless-stopped

  #kafka related vars

  confluent_platform_version: 5.3.1
  zoonavigator_version: 0.5.1
  zoonavigator_api_version: 0.6.2
  ksql_db_version: 0.6.0
  schema_registry_ui_version: latest
  kafka_connect_ui_version: latest
  kafka_manager_version: latest
  kafka_kafdrop_version: latest
  kafka_kadmin_version: latest
  kafka_kafkahq_version: latest
  kafka_burrow_version: 1.2.0
  kafka_burrow_ui_version: 1.1.0
  kafka_burrow_dashboard_version: 1.0.4

  #hadoop related vars
  hadoop_version : 2.0.0-hadoop3.1.3-java8

  #spark
  spark_version: 2.4.4-hadoop2.7 
  spark_livy_version: latest

  #hive
  hive_version: 2.3.4-postgresql-metastore-s3

  #atlas
  atlas_verion: 2.0.0

  #cassandra
  cassandra_version: 3

  #elasticsearch
  elasticsearch_version: 6.7.0
  dejavu_version: 3.4.0
  cerebro_version: latest
  elasticsearchhq_version: latest

  #amunden
  amundsen_frontend_version: 1.0.7
  amundsen_search_version: 1.1.1
  amundsen_metadata_version: 1.0.12

  #hue
  hue_version: latest
  hue_postgres_version: 10

  #streamsets
  streamsets_version: latest
  streamsets_transformer_version: latest
  streamsets_edge_version_AMD: amd64-3.12.0
  streamsets_edge_version_ARM: arm32v6-3.12.0

  #nifi
  nifi_version: latest

  #zepelin
  zeppelin_version: 0.8.2-hadoop2.7-spark2.4.4

  #jupyter
  jupyter_minimal_version: latest
  jupyter_r_version: latest
  jupyter_scipy_version: latest
  jupyter_tensorflow_version: latest
  jupyter_datascience_version: latest
  # - 2.4.0 tag 59b402ce701d
  # - 2.4.3 tag abdb27a6dfbb
  # - 2.4.4 tag 7a0c7325e470
  jupyter_all_spark_version: 7a0c7325e470
  #graphana
  graphana_version: 6.5.0
  #kibana
  kibana_version: 6.6.0 # should match elasticsearch version (minor increases should work though)

  #redis
  redis_version: 5.0.7
  redis_commander_version : latest

  #mongo
  mongodb_version: 3.4
  mongo_express_version: 0.49
  mongo_admin_version: latest

  #solr
  solr_version: 8

  #neo4j
  neo4j_version: 3.5

  #   influxdb
  influxdb_version: latest
  chronograf_version: latest
  kapacitor_version: latest
  telegraf_version: latest

  influxdb2_version: 2.0.0-alpha

  #prometheus
  prometheus_version: latest

  #tile38
  tile38_version: latest

  #mysql
  mysql_version: 8

  #sqlserver
  sqlserver_version: 2017-latest-ubuntu

  #postgres
  postgres_version: latest

  #adminer
  adminer_version: latest

  #axon
  axon_version: 4.2.4

  #mqtt
  mosquitto_version: latest
  hivemq3_version: latest
  hivemq4_version: latest
  hivemq_mqtt_web_client_version: latest
  activemq_version: 5.15.9

  #ftp
  ftp_pureftpd_version: latest
  ftp_filezilla_version: latest

  minio_version: latest
  awscli_version: latest
  portainer_version: 1.22.2

templates:
  - src: templates/docker-compose.yml.j2
    dest: stacks/docker-compose.yml
    include_vars :
      - vars/default-values.yml
      - /tmp/custom-values.yml

  - src: templates/mdps-services.yml.j2
    dest: stacks/mdps-services.yml
    include_vars :
      - vars/default-values.yml
      - /tmp/custom-values.yml
