---

#include_vars:
#  - vars-global.yml
vars:
  stack_name: tvd-generator
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  container_restart_policy: unless-stopped

  #kafka related vars

  CONFLUENT_PLATFORM_version: 5.4.0
  ZOONAVIGATOR_version: 0.5.1
  ZOONAVIGATOR_API_version: 0.6.2
  KSQLDB_version: 0.6.0
  SCHEMA_REGISTRY_UI_version: latest
  KAFKA_CONNECT_UI_version: latest
  KAFKA_MANAGER_version: latest
  KAFKA_KAFDROP_version: latest
  KAFKA_KADMIN_version: latest
  KAFKA_KAFKAHQ_version: latest
  KAFKA_BURROW_version: 1.2.0
  KAFKA_BURROW_UI_version: 1.1.0
  KAFKA_BURROW_DASHBOARD_version: 1.0.4

  #hadoop related vars
  HADOOP_version : 2.0.0-hadoop3.1.3-java8

  #spark
  SPARK_version: 2.4.4-hadoop2.7 

  #spark
  #SPARK3_version: 3.0.0pv2-hadoop2.7 

  # apache livy
  LIVY_version: latest

  #hive
  HIVE_version: 2.3.4-postgresql-metastore-s3

  #atlas
  ATLAS_version: 2.0.0

  #amunden
  AMUNDSEN_FRONTEND_version: 1.2.0
  AMUNDSEN_SEARCH_version: 1.4.3
  AMUNDSEN_METADATA_version: 1.1.7

  #cassandra
  CASSANDRA_version: 3

  #elasticsearch
  ELASTICSEARCH_version: 6.7.0
  DEJAVU_version: 3.4.0
  CEREBRO_version: latest
  ELASTICSEARCHHQ_version: latest

  #hue
  HUE_version: latest
  HUE_POSTGRES_version: 10

  #streamsets
  STREAMSETS_version: latest
  STREAMSETS_TRANSFORMER_version: latest
  STREAMSETS_EDGE_version: 3.12.0

  #nifi
  NIFI_version: latest

  #zepelin
  ZEPPELIN_version: 0.8.2-hadoop2.7-spark2.4.4

  #jupyter
  JUPYTER_MINIMAL_version: latest
  JUPYTER_R_version: latest
  JUPYTER_SCIPY_version: latest
  JUPYTER_TENSORFLOW_version: latest
  JUPYTER_DATASCIENCE_version: latest
  # - 2.4.0 tag 59b402ce701d
  # - 2.4.3 tag abdb27a6dfbb
  # - 2.4.4 tag 7a0c7325e470
  JUPYTER_ALL_SPARK_version: 7a0c7325e470

  #grafana
  GRAFANA_version: 6.5.0
  #kibana
  KIBANA_version: 6.6.0 # should match elasticsearch version (minor increases should work though)

  #redis
  REDIS_version: 5.0.7
  REDIS_COMMANDER_version : latest

  #mongo
  MONGO_version: 3.4
  MONGO_EXPRESS_version: 0.49
  MONGO_ADMIN_version: latest

  #solr
  SOLR_version: 8

  #neo4j
  NEO4J_version: latest

  #   influxdb
  INFLUXDB_version: latest
  CHRONOGRAF_version: latest
  KAPACITOR_version: latest
  TELEGRAF_version: latest
  INFLUXDB_UI_version: latest

  INFLUXDB2_version: 2.0.0-beta

  #prometheus
  PROMETHEUS_version: latest
  PROMETHEUS_PUSHGATEWAY_version: latest

  #tile38
  TILE38_version: latest

  #mysql
  MYSQL_version: 8

  #sqlserver
  SQLSERVER_version: 2017-latest-ubuntu

  #postgres
  POSTGRES_version: latest

  #timescaledb
  TIMESCALEDB_version: latest

  #adminer
  adminer_version: latest

  #axon
  AXON_version: 4.2.4

  #mqtt
  MOSQUITTO_version: latest
  HIVEMQ3_version: latest
  HIVEMQ4_version: latest
  HIVEMQ_MQTT_WEB_CLIENT_version: latest

  #ActiveMQ
  ACTIVEMQ_version: 5.15.9

  #ftp
  FTP_PUREFTPD_version: latest
  FTP_FILEZILLA_version: latest

  MINIO_version: latest
  AWSCLI_version: latest

  # Portainer
  PORTAINER_version: latest
  CADVISOR_version: latest

templates:
  - src: templates/docker-compose.yml.j2
    dest: destination/docker-compose.yml
    include_vars :
      - vars/config.yml
      - /tmp/config.yml

