---

#include_vars:
#  - vars-global.yml
vars:
  stack_name: tvd-generator
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  container_restart_policy: unless-stopped

  #kafka related vars

  confluent_platform_version: 5.3.1
  zoonavigator_version: 0.5.1
  zoonavigator_api_version: 0.6.2
  ksql_db_version: 0.6.0
  schema_registry_ui_version: latest
  kafka_connect_ui_version: latest
  kafka_manager_version: latest
  kafka_kafdrop_version: latest
  kafka_kadmin_version: latest
  kafka_kafkahq_version: latest
  kafka_burrow_version: 1.2.0
  kafka_burrow_ui_version: 1.1.0
  kafka_burrow_dashboard_version: 1.0.4

  #hadoop related vars
  tvd_hadoop_version : 2.0.0-hadoop3.1.3-java8

  #spark
  tvd_spark_version: 2.4.4-hadoop2.7 
  tvd_spark_livy_version: latest

  #hive
  hive_version: 2.3.4-postgresql-metastore-s3

  #atlas
  tvd_atlas_verion: 2.0.0

  #cassandra
  cassandra_version: 3

  #elasticsearch
  elasticsearch_version: 6.7.0
  dejavu_version: 3.4.0
  cerebro_version: latest
  elasticsearchhq_version: latest

  #amunden
  amundsen_frontend_version: 1.0.7
  amundsen_search_version: 1.1.1
  amundsen_metadata_version: 1.0.12

  #hue
  hue_version: latest
  hue_postgres_version: 10

  #streamsets
  tvd_streamsets_version: latest

  #nifi
  nifi_version: latest

  #zepelin
  tvd_zeppelin_version: 0.8.2-hadoop2.7-spark2.4.4

  #jupyter
  jupyter_version: abdb27a6dfbb
  #graphana
  graphana_version: 6.5.0
  #kibana
  kibana_version: 6.6.0 # should match elasticsearch version (minor increases should work though)

  #redis
  redis_version: 5.0.7
  redis_commander_version : latest

  #mongo
  mongodb_version: 3.4
  mongo_express_version: 0.49
  mongo_admin_version: latest

  #solr
  solr_version: 8

  #neo4j
  neo4j_version: 3.5

  #tile38
  tile38_version: 1.19.1

  #mysql
  mysql_version: 8

  #sqlserver
  sqlserver_version: 2017-latest-ubuntu

  #postgres
  postgres_version: latest

  #adminer
  adminer_version: latest

  #axon
  axon_version: 4.2.4

  #mqtt
  mosquitto_version: latest
  hivemq3_version: latest
  hivemq_mqtt_web_client_version: latest
  activemq_version: 5.15.9

  #ftp
  ftp_pureftpd_version: latest
  ftp_filezilla_version: latest

  minio_version: latest
  awscli_version: latest
  portainer_version: 1.22.2

templates:
  - src: templates/docker-compose.yml.j2
    dest: stacks/docker-compose.yml
    include_vars :
      - vars/default-values.yml
      - /tmp/custom-values.yml

  - src: templates/service.md.j2
    dest: stacks/Service.md
    include_vars :
      - vars/default-values.yml
      - /tmp/custom-values.yml
