---

#include_vars:
#  - vars-global.yml
vars:
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  container_restart_policy: unless-stopped

  #kafka related vars

  CONFLUENT_PLATFORM_version: 6.1.0
  AZKARRA_version: 0.7.4
  APICURIO_REGISTRY_version: 1.3.2.Final
  ZOONAVIGATOR_version: latest
  ZOONAVIGATOR_API_version: latest
  KAFKA_KSQLDB_version: 0.15.0
  KAFKACAT_version: 1.6.0
  SCHEMA_REGISTRY_UI_version: latest
  KAFKA_TOPICS_UI_version: latest
  KAFKA_CONNECT_UI_version: latest
  KAFKA_CMAK_version: latest
  KAFKA_KAFDROP_version: latest
  KAFKA_KADMIN_version: latest
  KAFKA_AKHQ_version: latest
  KAFKA_UI_version: latest
  KAFKA_EAGLE_version: latest
  STREAMS_EXPLORER_version: latest
  KAFKA_BURROW_version: 1.2.0
  KAFKA_BURROW_UI_version: 1.1.0
  KAFKA_BURROW_DASHBOARD_version: 1.0.4

  #hadoop related vars (if you change hadoop version, make sure to do it in both properties!!)
  HADOOP_image_version: 2.0.0-hadoop3.2.1-java8
  HADOOP_version : 3.2.1

  #spark
  SPARK2_version: 2.4.7
  SPARK3_version: 3.0.1

  # apache livy
  LIVY_version: 0.7.0-incubating

  #hive
  HIVE_version: 3.1.2
  HIVE_version_suffix: postgresql-metastore-s3
  HIVE_METASTORE_DB_version: 3.1.0-postgres9.5.3

  #apache range
  RANGER_version: 2.1.0
  RANGER_postgresql_version: 12

  #atlas
  ATLAS_version: 2.1.0

  #datahub
  DATAHUB_version: v0.7.0

  #amunden
  AMUNDSEN_FRONTEND_version: 3.0.0
  AMUNDSEN_SEARCH_version: 2.4.1
  AMUNDSEN_METADATA_version: 3.0.0

  #Marquez
  MARQUEZ_version: 0.12.2
  MARQUEZ_WEB_version: 0.12.2

  #cassandra
  CASSANDRA_version: 3

  # DataStax Enterprise (DSE)
  DATASTAX_version: 6.7.7

  #elasticsearch
  ELASTICSEARCH_version: 7.10.1
  DEJAVU_version: latest
  CEREBRO_version: latest
  ELASTICSEARCHHQ_version: latest

  #hue
  HUE_version: 4.8.0
  HUE_POSTGRES_version: 10

  #streamsets
  STREAMSETS_version: 3.21.0
  STREAMSETS_TRANSFORMER_version: 3.17.0
  STREAMSETS_EDGE_version: 3.13.0

  #nifi
  NIFI_version: 1.12.1
  NIFI_REGISTRY_version: 0.8.0

  #nodered
  NODERED_version: 1.1.3

  # StreamSheets
  STREAMSHEETS_version: 2.2-milestone

  # Spring Cloud Data Flow
  SPRING_DATAFLOW_version: 2.7.0
  SPRING_SKIPPER_version: 2.6.0

  #sqoop
  SQOOP_version: 1.4.7-hadoop3.2

  #nodered
  AIRFLOW_version: 1.10.13

  #zepelin
  ZEPPELIN_version: 0.9.0

  #jupyter
  JUPYTER_MINIMAL_version: latest
  JUPYTER_R_version: latest
  JUPYTER_SCIPY_version: latest
  JUPYTER_TENSORFLOW_version: latest
  JUPYTER_DATASCIENCE_version: latest
  # - 2.4.0 tag 59b402ce701d
  # - 2.4.3 tag abdb27a6dfbb
  # - 2.4.4 tag 7a0c7325e470
  # - 2.4.5 tag f9b134f7bd08
  JUPYTER_ALL_SPARK_version: f9b134f7bd08

  # dataiku data science studio
  DATAIKU_DSS_version: 8.0.2

  #grafana
  GRAFANA_version: 7.3.4
  #kibana
  KIBANA_version: 7.10.1  # should match elasticsearch version (minor increases should work though)

  # Apache Superset
  SUPERSET_version: latest-dev
  REDASH_version: preview

  # Smashing Dashboard
  SMASHING_version: 1.3.0

  # Tipboard Dashboard
  TIBOARD_version: 1.4.3

  # Chartboard Dahsboard (fork of tipboard)
  CHARTBOARD_enable: latest

  #Memcached
  MEMCACHED_version: 1.6.9

  #redis
  REDIS_version: 6.0.9
  REDIS_INSIGHT_version : latest
  REDIS_COMMANDER_version : latest

  #mongo
  MONGO_version: 4.4.2
  MONGO_EXPRESS_version: latest
  MONGO_ADMIN_version: latest

  #solr
  SOLR_version: 8.6

  #neo4j
  NEO4J_version: 4.2.0

  #Dgraph
  DGRAPH_version: v20.11.1

  #stardog
  STARDOG_version: 7.4.5-java11-preview
  #stardog-studio
  STARDOG_STUDIO_version: 1.30.0

  #graphdb
  GRAPHDB_version: 9.6.0

  #   influxdb
  INFLUXDB_version: 1.8
  CHRONOGRAF_version: 1.8
  KAPACITOR_version: 1.5
  TELEGRAF_version: 1.15
  INFLUXDB_UI_version: latest

  INFLUXDB2_version: v2.0.2

  # Kudu
  KUDU_version: 1.13

  # Druid
  DRUID_version: 0.20.0

  #prometheus
  PROMETHEUS_version: v2.23.0
  PROMETHEUS_PUSHGATEWAY_version: v1.3.0

  #tile38
  TILE38_version: 1.22.5

  # Yugabyte
  YUGABYTE_version: 2.5.0.0-b2

  #oracle
  ORACLE_XE_version: 11.2.0.2-xe
  ORACLE_EE_version: 18.9.0.0
  ORACLE_REST_DATA_SERVICE_version: latest

  #mysql
  MYSQL_version: 8

  #sqlserver
  SQLSERVER_version: 2019-latest

  #postgres
  POSTGRESQL_version: 13

  #postgres
  POSTGREST_version: latest

  #timescaledb
  TIMESCALEDB_version: latest-pg12

  #adminer
  ADMINER_version: latest

  #adminer
  CLOUDBEAVER_version: latest

  #SQLPad
  SQLPAD_version: latest

  # QUIX
  QUIX_version: latest

  #axon
  AXON_version: 4.4.5

  #presto
  TRINO_version: 353
  STARBURSTDATA_version: 350-e.5
  TRINO_CLI_version: latest

  #presto
  PRESTO_version: 0.249
  AHANA_version: 0.249
  PRESTO_CLI_version: latest

  #dremio
  DREMIO_version: 11.0

  #apache drill
  DRILL_version: 1.16.0-alpine

  #hasura
  HASURA_version: v2.0.0-alpha.6

  #GraphQL Mesh
  GRAPHQL_MESH_version: latest-all

  #mqtt
  MOSQUITTO_version: 2.0
  HIVEMQ3_version: 3.4.7
  HIVEMQ4_version: 4.5.0
  HIVEMQ_MQTT_WEB_CLIENT_version: latest
  CEDALO_MANAGEMENT_CENTER_version: 2.1

  # Thingsboard
  THINGSBOARD_version: 3.2.1

  #ActiveMQ
  ACTIVEMQ_version: 5.15.9

  #RabbitMQ
  RABBITMQ_version: 3.8-management

  #ftp
  FTP_PUREFTPD_version: latest
  FTP_FILEZILLA_version: latest

  # Penthao Webspoon
  PENTHAO_version: 0.9.0.22

  # Minio
  MINIO_version: RELEASE.2021-02-01T22-56-52Z
  MINIO_MC_version: latest

  MINIO_CONSOLE_version: latest
  ADMINIO_UI_version: latest
  ADMINIO_API_version: latest
  FILESTASH_version: latest
  S3MANAGER_version: latest
  AWSCLI_version: latest

  # Code Server
  CODE_SERVER_version: latest

  # File Browser
  FILE_BROWSER_version: latest

  # Vault
  VAULT_version: 1.6.0

  # Keyclock
  KEYCLOCK_version: 10.0.1

  # Swagger API Management
  SWAGGER_EDITOR_version: latest
  SWAGGER_UI_version: latest

  # Postman
  POSTMAN_version: latest

  # Microcks 
  MICROCKS_version: latest

  # Portainer
  PORTAINER_version: 2.0.0-alpine
  CADVISOR_version: v0.36.0
  HAWTIO_version: latest
  WETTY_version: latest

  MARKDOWN_VIEWER_version: latest
  LOG4BRAINS_version: latest

  WATCHTOWER_version: 1.1.6

  #Python
  PYTHON_version: 3.8.1-alpine3.11

templates:
  - src: templates/docker-compose.yml.j2
    dest: destination/docker-compose.yml
    include_vars :
      - vars/config.yml
      - /tmp/config.yml
