---

#include_vars:
#  - vars-global.yml
vars:
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  container_restart_policy: unless-stopped

  #kafka related vars

  CONFLUENT_PLATFORM_version: 5.5.0
  ZOONAVIGATOR_version: latest
  ZOONAVIGATOR_API_version: latest
  KAFKA_KSQLDB_version: 0.9.0
  KAFKACAT_version: 1.5.0
  SCHEMA_REGISTRY_UI_version: latest
  KAFKA_TOPICS_UI_version: latest
  KAFKA_CONNECT_UI_version: latest
  KAFKA_CMAK_version: latest
  KAFKA_KAFDROP_version: latest
  KAFKA_KADMIN_version: latest
  KAFKA_AKHQ_version: latest
  KAFKA_BURROW_version: 1.2.0
  KAFKA_BURROW_UI_version: 1.1.0
  KAFKA_BURROW_DASHBOARD_version: 1.0.4

  #hadoop related vars
  HADOOP_version : 2.0.0-hadoop3.2.1-java8

  #spark
  SPARK_version: 2.4.5-hadoop2.8 

  #spark
  #SPARK3_version: 3.0.0pv2-hadoop2.7 

  # apache livy
  LIVY_version: latest

  #hive
  HIVE_version: 3.1.2
  HIVE_version_suffix: postgresql-metastore-s3
  HIVE_METASTORE_DB_version: 3.1.0-postgres9.5.3

  #apache range
  RANGER_version: latest
  RANGER_POSTGRES_version: latest

  #atlas
  ATLAS_version: 2.0.0

  #datahub
  DATAHUB_version: latest

  #amunden
  AMUNDSEN_FRONTEND_version: 1.2.0
  AMUNDSEN_SEARCH_version: 1.4.3
  AMUNDSEN_METADATA_version: 1.1.7

  #Marquez
  MARQUEZ_version: latest 
  MARQUEZ_WEB_version: latest

  #cassandra
  CASSANDRA_version: 3

  # DataStax Enterprise (DSE)
  DATASTAX_version: 6.7.7

  #elasticsearch
  ELASTICSEARCH_version: 6.7.0
  DEJAVU_version: latest
  CEREBRO_version: latest
  ELASTICSEARCHHQ_version: latest

  #hue
  HUE_version: latest
  HUE_POSTGRES_version: 10

  #streamsets
  STREAMSETS_version: latest
  STREAMSETS_TRANSFORMER_version: latest
  STREAMSETS_EDGE_version: 3.13.0

  #nifi
  NIFI_version: latest

  #nodered
  NODERED_version: latest

  #sqoop
  SQOOP_version: latest

  #nodered
  AIRFLOW_version: latest

  #zepelin
  ZEPPELIN_version: 0.8.2-spark2.4-hadoop2.8

  #jupyter
  JUPYTER_MINIMAL_version: latest
  JUPYTER_R_version: latest
  JUPYTER_SCIPY_version: latest
  JUPYTER_TENSORFLOW_version: latest
  JUPYTER_DATASCIENCE_version: latest
  # - 2.4.0 tag 59b402ce701d
  # - 2.4.3 tag abdb27a6dfbb
  # - 2.4.4 tag 7a0c7325e470
  # - 2.4.5 tag f9b134f7bd08
  JUPYTER_ALL_SPARK_version: f9b134f7bd08

  #grafana
  GRAFANA_version: 6.5.0
  #kibana
  KIBANA_version: 6.6.0 # should match elasticsearch version (minor increases should work though)

  # Apache Superset
  SUPERSET_version: latest
  
  #redis
  REDIS_version: latest
  REDIS_COMMANDER_version : latest

  #mongo
  MONGO_version: latest
  MONGO_EXPRESS_version: latest
  MONGO_ADMIN_version: latest

  #solr
  SOLR_version: 8

  #neo4j
  NEO4J_version: latest

  #   influxdb
  INFLUXDB_version: latest
  CHRONOGRAF_version: latest
  KAPACITOR_version: latest
  TELEGRAF_version: latest
  INFLUXDB_UI_version: latest

  INFLUXDB2_version: 2.0.0-beta

  # Kudo
  KUDO_version: latest

  # Druid
  DRUID_version: 0.16.1-incubating

  #prometheus
  PROMETHEUS_version: latest
  PROMETHEUS_PUSHGATEWAY_version: latest

  #tile38
  TILE38_version: latest

  # Yugabyte
  YUGABYTE_version: latest

  #oracle
  ORACLE_XE_version: 11.2.0.2-xe 
  ORACLE_EE_version: 18.9.0.0
  ORACLE_REST_DATA_SERVICE_version: latest
  
  #mysql
  MYSQL_version: 8

  #sqlserver
  SQLSERVER_version: 2017-latest-ubuntu

  #postgres
  POSTGRES_version: latest

  #timescaledb
  TIMESCALEDB_version: latest

  #adminer
  ADMINER_version: latest

  #adminer
  CLOUDBEAVER_version: latest

  #axon
  AXON_version: latest

  #presto
  PRESTO_version: latest

  #dremio
  DREMIO_version: latest

  #apache drill
  DRILL_version: latest

  #mqtt
  MOSQUITTO_version: latest
  HIVEMQ3_version: latest
  HIVEMQ4_version: latest
  HIVEMQ_MQTT_WEB_CLIENT_version: latest

  #ActiveMQ
  ACTIVEMQ_version: 5.15.9
  
  #RabbitMQ
  RABBITMQ_version: 3-management

  #ftp
  FTP_PUREFTPD_version: latest
  FTP_FILEZILLA_version: latest

  # Penthao Webspoon
  PENTHAO_version: latest

  MINIO_version: latest
  AWSCLI_version: latest

  # Portainer
  CODE_SERVER_version: latest

  # Vault
  VAULT_version: latest

  # Swagger API Management
  SWAGGER_EDITOR_version: latest
  SWAGGER_UI_version: latest

  # Portainer
  PORTAINER_version: latest
  CADVISOR_version: latest
  HAWTIO_version: latest

  #Python
  PYTHON_version: 3.8.1-alpine3.11

templates:
  - src: templates/docker-compose.yml.j2
    dest: destination/docker-compose.yml
    include_vars :
      - vars/config.yml
      - /tmp/config.yml

